name    'jhoblitt-ipmi'
version '1.2.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-ipmi'
source 'https://github.com/jhoblitt/puppet-ipmi.git'
summary 'manages the OpenIPMI package'
description 'manages the OpenIPMI package'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
